tg21

diff --git a/.github/workflows/project_ci.yml b/.github/workflows/project_ci.yml
--- a/.github/workflows/project_ci.yml
+++ b/.github/workflows/project_ci.yml
@@ -115,7 +115,6 @@
 # #     token: ${{ secrets.TELEGRAM_TOKEN }}
 # #     message: ${{ env.message }}
 
-
 # name: CI Pipeline
 
 # on:
@@ -187,7 +186,6 @@
 #           echo "Output 1: ${{ needs['lint-and-type-check'].outputs.output_1 }}"
 #           echo "Message: $message"
 
-
 # name: CI Pipeline
 
 # on:
@@ -239,7 +237,93 @@
 #       - name: Print steps
 #         run: echo ${{ toJSON(steps) }}
 
+# name: CI Pipeline
 
+# on:
+#   pull_request:
+#     branches:
+#       - main
+#   push:
+#     branches:
+#       - main
+
+# env:
+#   TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Добавьте ваш Telegram Bot API токен в секреты GitHub
+#   TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # Добавьте ваш Telegram chat ID в секреты GitHub
+
+# jobs:
+#   lint-and-type-check:
+#     runs-on: ubuntu-latest
+
+#     strategy:
+#       matrix:
+#         python-version: ["3.10", "3.11"]
+
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v4
+
+#       - name: Set up Python ${{ matrix.python-version }}
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: ${{ matrix.python-version }}
+
+#       - name: Install dependencies
+#         run: |
+#           python -m pip install --upgrade pip
+#           pip install wemake-python-styleguide mypy
+#           pip install --upgrade flake8 flake8-quotes flake8-html
+
+#       - name: Run lint and generate HTML report
+#         run: |
+#           mkdir -p reports
+#           flake8 . --format=html --htmldir=reports/lint_report || true
+
+#       - name: Run type check
+#         run: python -m mypy .
+
+#       - name: Fail workflow
+#         run: exit 1
+
+#       - name: Archive HTML report
+#         if: matrix.python-version == '3.10'
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: lint-report
+#           path: reports/lint_report
+
+#       - name: Capture Failed Step
+#         if: failure()
+#         id: capture-failure
+#         run: |
+#           echo ${{ toJSON(steps) }}
+#           echo "failed_step=${{ steps.*.name }}" >> $GITHUB_ENV
+
+#   notify:
+#     runs-on: ubuntu-latest
+#     needs: lint-and-type-check
+#     if: always()
+
+#     steps:
+#       - name: Determine status and send Telegram notification
+#         run: |
+#           PROJECT_NAME="${{ github.repository }}"
+#           COMMIT_HASH="${{ github.sha }}"
+#           STATUS="successfully"
+#           FAILED_STEP=""
+
+#           if [ "${{ needs.lint-and-type-check.result }}" != "success" ]; then
+#             STATUS="with error"
+#             FAILED_STEP=$(echo "Failed on step: ${{ env.failed_step }}")
+#           fi
+
+#           MESSAGE="${PROJECT_NAME}: Pipeline for commit ${COMMIT_HASH} finished ${STATUS}! ${FAILED_STEP}"
+
+#           echo ${MESSAGE}
+
+#         #   curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
+#         #   -d chat_id="${TELEGRAM_CHAT_ID}" \
+#         #   -d text="${MESSAGE}"
 
 name: CI Pipeline
 
@@ -252,8 +336,8 @@ on:
       - main
 
 env:
-  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Добавьте ваш Telegram Bot API токен в секреты GitHub
-  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # Добавьте ваш Telegram chat ID в секреты GitHub
+  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
+  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
 
 jobs:
   lint-and-type-check:
@@ -262,6 +346,9 @@ jobs:
     strategy:
       matrix:
         python-version: ["3.10", "3.11"]
+
+    outputs:
+      failed_step: ${{ steps.capture-failure.outputs.failed_step }}
 
     steps:
       - name: Checkout code
@@ -279,15 +366,14 @@ jobs:
           pip install --upgrade flake8 flake8-quotes flake8-html
 
       - name: Run lint and generate HTML report
+        id: run-lint-and-generate-html-report
         run: |
           mkdir -p reports
           flake8 . --format=html --htmldir=reports/lint_report || true
 
       - name: Run type check
+        id: run-type-check
         run: python -m mypy .
-
-      - name: Fail workflow
-        run: exit 1
 
       - name: Archive HTML report
         if: matrix.python-version == '3.10'
@@ -297,11 +383,14 @@ jobs:
           path: reports/lint_report
 
       - name: Capture Failed Step
-        if: failure()
         id: capture-failure
         run: |
-          echo ${{ toJSON(steps) }}
-          echo "failed_step=${{ steps.*.name }}" >> $GITHUB_ENV
+          if [ "${{ steps.run-lint-and-generate-html-report.outcome }}" == "failure" ]; then
+            echo "failed_step=Run lint and generate HTML report" >> $GITHUB_ENV
+          elif [ "${{ steps.run-type-check.outcome }}" == "failure" ]; then
+            echo "failed_step=Run type check" >> $GITHUB_ENV
+          else
+            echo "failed_step=All steps passed" >> $GITHUB_ENV
 
   notify:
     runs-on: ubuntu-latest
@@ -309,20 +398,20 @@ jobs:
     if: always()
 
     steps:
-      - name: Determine status and send Telegram notification
+      - name: Send Telegram notification
         run: |
           PROJECT_NAME="${{ github.repository }}"
           COMMIT_HASH="${{ github.sha }}"
           STATUS="successfully"
-          FAILED_STEP=""
+          FAILED_STEP="${{ needs.lint-and-type-check.outputs.failed_step }}"
 
-          if [ "${{ needs.lint-and-type-check.result }}" != "success" ]; then
+          if [ "$FAILED_STEP" != "All steps passed" ]; then
             STATUS="with error"
-            FAILED_STEP=$(echo "Failed on step: ${{ env.failed_step }}")
+            MESSAGE="${PROJECT_NAME}: Pipeline for commit ${COMMIT_HASH} finished ${STATUS}! ${FAILED_STEP} failed."
+          else
+            MESSAGE="${PROJECT_NAME}: Pipeline for commit ${COMMIT_HASH} finished ${STATUS}!"
           fi
 
-          MESSAGE="${PROJECT_NAME}: Pipeline for commit ${COMMIT_HASH} finished ${STATUS}! ${FAILED_STEP}"
-
-        #   curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
-        #   -d chat_id="${TELEGRAM_CHAT_ID}" \
-        #   -d text="${MESSAGE}"
+          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
+          -d chat_id="${TELEGRAM_CHAT_ID}" \
+          -d text="${MESSAGE}"
