tg-0

diff --git a/.github/workflows/project_ci.yml b/.github/workflows/project_ci.yml
--- a/.github/workflows/project_ci.yml
+++ b/.github/workflows/project_ci.yml
@@ -14,39 +14,54 @@ jobs:
 
     strategy:
       matrix:
-        python-version: ['3.11', '3.10']
+        python-version: ["3.11", "3.10"]
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install wemake-python-styleguide mypy
-        pip install --upgrade flake8 flake8-quotes flake8-html
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install wemake-python-styleguide mypy
+          pip install --upgrade flake8 flake8-quotes flake8-html
 
-    - name: Run lint and generate HTML report
-      run: |
-        mkdir -p reports
-        flake8 . --format=html --htmldir=reports/lint_report || true
+      - name: Run lint and generate HTML report
+        run: |
+          mkdir -p reports
+          flake8 . --format=html --htmldir=reports/lint_report || true
 
-    - name: Run type check
-      run: python -m mypy .
+      - name: Run type check
+        run: python -m mypy .
 
-    - name: Archive HTML report
-      if: ${{ matrix.python-version == '3.10' }}
-      uses: actions/upload-artifact@v4
-      with:
-        name: lint-report
-        path: reports/lint_report
+      - name: Archive HTML report
+        if: ${{ matrix.python-version == '3.10' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: lint-report
+          path: reports/lint_report
 
-    - name: Fail the job if lint errors were found
-      if: ${{ matrix.python-version == '3.10' }}
-      run: |
-        flake8 . || exit 1
+      - name: Fail the job if lint errors were found
+        if: ${{ matrix.python-version == '3.10' }}
+        run: |
+          flake8 . || exit 1
+
+  notify:
+    runs-on: ubuntu-latest
+    needs: lint-and-type-check
+    steps:
+      - name: Send Telegram Notification
+        uses: appleboy/telegram-action@v0.1.0
+        with:
+          to: ${{ secrets.TELEGRAM_CHAT_ID }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          message: |
+          ${{ github.event.repository.name }}: Pipeline for ${{ github.sha }} finished ${{ job.status }}!
+        #   {% if failure() %}
+        #   ${{ job.name }} failed
+        #   {% endif %}
